### ISSUE TITLE
关于 React-SiriWave 的一些疑问

### ISSUE THREAD

**Issue by bouquetrender** [JoeyKo/React-SiriWave#1]
我从 npm 搜到了你发布的 React-SiriWave 不过看代码是空的。因为项目需要我之前也有将 siriwave 做成 react 组件，但传参不和 siriwave.js 一致。现在想着把代码重新修改完善后发布，如果你正在开发那么我就不再改旧版等你 release。

**Comment by JoeyKo** [comment]
@Sakuyakun 不好意思哈，最近工作上的事太多了，暂时没在开发，后续会补上

**Comment by bouquetrender** [comment]
@JoeyKo 😁好的
