### ISSUE TITLE
Can we access the start() function

### ISSUE THREAD

**Issue by linkb15** [JoeyKo/React-SiriWave#3]
**Is your feature request related to a problem? Please describe.**
I'm not sure how to start or stop the animation

**Describe the solution you'd like**
have an access for start or stop animation function using Ref or others solution we can come up with (maybe using hooks)

**Describe alternatives you've considered**
"-"

**Additional context**
"-"

**Comment by JoeyKo** [comment]
The latest version has supported `onInit` to get the siriwave instance
