### ISSUE TITLE
Property 'style' is a reserved react Keyword

### ISSUE THREAD

**Issue by MTheProgrammer** [JoeyKo/React-SiriWave#6]
**Describe the bug**
Usage:
`        <Siriwave style="ios" />`

returns warning:
`Line 31:68:  Style prop value must be an object  react/style-prop-object`

**To Reproduce**
Add Siriwave component with a style
` <Siriwave style="ios" />`

**Expected behavior**
No warning

**Additional context**
Change attribute name to e.g.: waveStyle

**Comment by JoeyKo** [comment]
The latest version has changed prop `style` to `theme`.
